import RecipeImage from './assets/images/recipe-thumbnail.jpg';

export const recipesData = [
  {
    id: 1,
    name: 'Spaghetti Bolognese',
    description:
      'Classic Italian pasta dish with a rich tomato and meat sauce.',
    image: RecipeImage,
    author: 'Chef John',
    datePosted: 1684972800,
    rating: 4.5,
    difficulty: 'Medium',
  },
  {
    id: 2,
    name: 'Chicken Tikka Masala',
    description:
      'Creamy and flavorful Indian chicken dish marinated in spices and yogurt.',
    image: RecipeImage,
    author: 'Chef Sarah',
    datePosted: 1685232000,
    rating: 4.8,
    difficulty: 'Medium',
  },
  {
    id: 3,
    name: 'Chocolate Chip Cookies',
    description: 'Classic homemade cookies with gooey chocolate chips.',
    image: RecipeImage,
    author: 'Baker Jane',
    datePosted: 1682899200,
    rating: 4.2,
    difficulty: 'Easy',
  },
  {
    id: 4,
    name: 'Caesar Salad',
    description:
      'Crisp romaine lettuce tossed in a creamy Caesar dressing, topped with croutons and Parmesan cheese.',
    image: RecipeImage,
    author: 'Chef Michael',
    datePosted: 1680220800,
    rating: 4.0,
    difficulty: 'Easy',
  },
  {
    id: 5,
    name: 'Mango Salsa',
    description:
      'Refreshing salsa made with fresh mangoes, red onions, cilantro, and lime juice.',
    image: RecipeImage,
    author: 'Chef Emily',
    datePosted: 1672531200,
    rating: 4.6,
    difficulty: 'Easy',
  },
  {
    id: 6,
    name: 'Beef Stir-Fry',
    description:
      'Quick and flavorful Asian-inspired stir-fried beef with vegetables.',
    image: RecipeImage,
    author: 'Chef David',
    datePosted: 1684800000,
    rating: 4.3,
    difficulty: 'Medium',
  },
  {
    id: 7,
    name: 'Caprese Salad',
    description:
      'Simple and delicious salad with ripe tomatoes, fresh mozzarella, and basil leaves.',
    image: RecipeImage,
    author: 'Chef Lisa',
    datePosted: 1702252800,
    rating: 4.7,
    difficulty: 'Easy',
  },
  {
    id: 8,
    name: 'Guacamole',
    description:
      'Creamy avocado dip with onions, tomatoes, lime juice, and spices.',
    image: RecipeImage,
    author: 'Chef Andrew',
    datePosted: 1692230400,
    rating: 4.4,
    difficulty: 'Easy',
  },
  {
    id: 9,
    name: 'Pancakes',
    description:
      'Fluffy breakfast pancakes served with maple syrup and butter.',
    image: RecipeImage,
    author: 'Baker Mark',
    datePosted: 1696982400,
    rating: 4.3,
    difficulty: 'Easy',
  },
  {
    id: 10,
    name: 'Berry Blast Smoothie Bowl',
    description:
      'A refreshing and nutritious smoothie bowl packed with a medley of mixed berries and toppings.',
    image: RecipeImage,
    author: 'Gordon Ramsey',
    datePosted: 1693180800,
    rating: 4.6,
    difficulty: 'Easy',
  },
];

export const recipeDetail = [
  {
    id: 1,
    title: 'Spaghetti Bolognese',
    servings: 4,
    ingredients: [
      '300g spaghetti',
      '500g ground beef',
      '1 onion, diced',
      '2 cloves of garlic, minced',
      '1 carrot, grated',
      '1 celery stalk, finely chopped',
      '400g canned crushed tomatoes',
      '2 tablespoons tomato paste',
      '1 teaspoon dried oregano',
      '1 teaspoon dried basil',
      '1/2 teaspoon salt',
      '1/4 teaspoon black pepper',
      '1/4 cup grated Parmesan cheese',
      'Fresh basil leaves, for garnish',
    ],
    instructions: [
      'Cook the spaghetti according to the package instructions. Drain and set aside.',
      'In a large skillet, cook the ground beef over medium heat until browned. Remove any excess fat.',
      'Add the diced onion, minced garlic, grated carrot, and chopped celery to the skillet. Cook until the vegetables are softened.',
      'Stir in the crushed tomatoes, tomato paste, dried oregano, dried basil, salt, and black pepper. Simmer for about 15 minutes, stirring occasionally.',
      'Add the cooked spaghetti to the skillet and toss to coat the pasta with the sauce.',
      'Serve the Spaghetti Bolognese hot, topped with grated Parmesan cheese and garnished with fresh basil leaves.',
    ],
    notes: [
      'You can customize this recipe by adding your favorite vegetables or herbs.',
      'Feel free to adjust the seasoning according to your taste.',
    ],
    image: RecipeImage,
    author: 'Chef John',
    datePosted: '2023-05-25',
    rating: 4.5,
    difficulty: 'Medium',
  },
  {
    id: 2,
    title: 'Chicken Tikka Masala',
    servings: 4,
    ingredients: [
      '500g boneless chicken, cut into cubes',
      '1 cup plain yogurt',
      '2 tablespoons lemon juice',
      '2 teaspoons ground cumin',
      '2 teaspoons ground paprika',
      '1 teaspoon ground turmeric',
      '1 teaspoon ground coriander',
      '1 teaspoon garam masala',
      '1/2 teaspoon chili powder',
      '2 tablespoons vegetable oil',
      '1 onion, finely chopped',
      '3 cloves of garlic, minced',
      '1-inch piece of ginger, grated',
      '1 can (400g) crushed tomatoes',
      '1 cup heavy cream',
      'Salt, to taste',
      'Fresh cilantro leaves, for garnish',
    ],
    instructions: [
      'In a bowl, combine the yogurt, lemon juice, ground cumin, ground paprika, ground turmeric, ground coriander, garam masala, and chili powder. Mix well.',
      'Add the chicken cubes to the marinade and coat them evenly. Let it marinate in the refrigerator for at least 1 hour, or overnight for best results.',
      'Heat the vegetable oil in a large skillet over medium heat. Add the chopped onion and cook until golden brown.',
      'Add the minced garlic and grated ginger to the skillet. Cook for another minute, stirring continuously.',
      'Add the marinated chicken along with the marinade to the skillet. Cook until the chicken is browned on all sides.',
      'Stir in the crushed tomatoes and simmer for about 15 minutes, allowing the flavors to blend together.',
      'Pour in the heavy cream and stir well. Cook for an additional 5 minutes.',
      'Season with salt to taste.',
      'Serve the Chicken Tikka Masala hot, garnished with fresh cilantro leaves. It pairs well with steamed rice or naan bread.',
    ],
    notes: [
      'For added smokiness, you can grill or broil the marinated chicken before adding it to the skillet.',
      'Adjust the level of spiciness by increasing or decreasing the amount of chili powder according to your preference.',
    ],
    image: RecipeImage,
    author: 'Chef Sarah',
    datePosted: '2023-05-28',
    rating: 4.8,
    difficulty: 'Medium',
  },
];
